set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_show_path 1     
set -g @tokyo-night-tmux_show_git 1             
set -g @resurrect-processes 'lazygit yazi'
set -g base-index 1
setw -g pane-base-index 1
set -g @plugin 'christoomey/vim-tmux-navigator' 
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g mouse on
run '~/.tmux/plugins/tpm/tpm'
