# --- General Settings ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Enable undercurl (useful for Neovim diagnostics)
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# --- Keybindings ---
set -g prefix C-a          # Changed from C-b to C-a
unbind C-b
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf \; display "Reloaded!"

# --- Theme Configuration ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

# Specific Tokyo Night options we picked
set -g @theme_variation 'storm'
set -g @theme_left_separator ''
set -g @theme_right_separator ''

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
