set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_show_path 1     
set -g @tokyo-night-tmux_show_git 1             
set -g @resurrect-processes 'posting yazi'
set -g base-index 1
setw -g pane-base-index 1
set -g @plugin 'christoomey/vim-tmux-navigator' 
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g mouse on
bind-key "T" run-shell "sesh connect \"$(
  sesh list -c --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --bind 'tab:down,btab:up' \
    --preview-window 'right:55%' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list -c --icons)' \
    --preview 'sesh preview {}'
)\""
set -g @plugin 'jimeh/tmuxifier'
set -g renumber-windows on
run '~/.tmux/plugins/tpm/tpm'
