include themes/noctalia.conf
hide_window_decorations yes
cursor_trail 1
window_padding_width 4

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
