[[session]]
name = "dotfiles"
startup_command = "tmuxifier load-window dotfiles"

[[session]]
name = "chordstrike"
startup_command = "tmuxifier load-window chordstrike"

[[session]]
name = "apis-cmssi"
startup_command = "tmuxifier load-window apis-cmssi"


[[session]]
name = "apis-api"
startup_command = "tmuxifier load-window apis-api"
