[default_session]
startup_command = "fish ~/.config/sesh/scripts/general.fish"

[[session]]
name = "dotfiles"
path = "~/dotfiles/"

[[session]]
name = "chordstrike"
path = "~/Projects/chordstrike/"
run = "fish ~/.config/sesh/scripts/godot.fish"

[[session]]
name = "apis-cmssi"
path = "~/Projects/apis-cmssi/"

[[session]]
name = "apis-api"
path = "~/Projects/apis-api/"

[[session]]
name = "cordilink"
path = "~/Projects/cordilink/"
