# Copy yanked files to the system clipboard
[[mgr.prepend_keymap]]
on  = "y"
run = [ "yank", 'plugin clipboard -- --action=copy' ]
desc = "Yank selected files (copy)"

# Keep behaviour consistent with cut
[[mgr.prepend_keymap]]
on  = "x"
run = [ "yank --cut", 'plugin clipboard -- --action=copy' ]
desc = "Yank selected files (cut)"

# Paste files from the system clipboard into the current directory
[[mgr.prepend_keymap]]
on  = "<C-p>"
run = [ 'plugin clipboard -- --action=paste' ]
desc = "Paste yanked system clipboard files"

# sudo cp/mv
[[mgr.prepend_keymap]]
on = ["R", "p", "p"]
run = "plugin sudo -- paste"
desc = "sudo paste"

# sudo cp/mv --force
[[mgr.prepend_keymap]]
on = ["R", "P"]
run = "plugin sudo -- paste --force"
desc = "sudo paste"

# sudo mv
[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin sudo -- rename"
desc = "sudo rename"

# sudo ln -s (absolute-path)
[[mgr.prepend_keymap]]
on = ["R", "p", "l"]
run = "plugin sudo -- link"
desc = "sudo link"

# sudo ln -s (relative-path)
[[mgr.prepend_keymap]]
on = ["R", "p", "r"]
run = "plugin sudo -- link --relative"
desc = "sudo link relative path"

# sudo ln
[[mgr.prepend_keymap]]
on = ["R", "p", "L"]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"

# sudo touch/mkdir
[[mgr.prepend_keymap]]
on = ["R", "a"]
run = "plugin sudo -- create"
desc = "sudo create"

# sudo trash
[[mgr.prepend_keymap]]
on = ["R", "d"]
run = "plugin sudo -- remove"
desc = "sudo trash"

# sudo delete
[[mgr.prepend_keymap]]
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"

# sudo chmod
[[mgr.prepend_keymap]]
on = ["R", "m"]
run = "plugin sudo -- chmod"
desc = "sudo chmod"

# sudoedit
[[mgr.prepend_keymap]]
on = ["R", "e"]
run = 'shell "sudoedit $@"'
desc = "sudoedit selected file"
