[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml"
]

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 10
y = 10

