[bar.default]
background_opacity = 0.5
capsule = true
end = [ "tray", "network", "bluetooth", "volume", "brightness", "battery", "control-center" ]
start = [ "launcher", "workspaces", "session", "Hibernate" ]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 960.0
    cy = 881.5
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 1920.0
    cy = 1961.5
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 960.0
    cy = 720.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

[shell]
font_family = "JetBrains Mono"
polkit_agent = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.panel]
    transparency_mode = "glass"

[theme]
builtin = "Tokyo-Night"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk4", "kitty", "niri", "qt" ]
    community_ids = [ "opencode", "pywalfox", "discord", "telegram", "obs", "zathura", "bat", "lazygit", "yazi" ]

[wallpaper]
directory = "/home/julio/dotfiles/others/backgrounds"

    [wallpaper.default]
    path = "/home/julio/dotfiles/others/backgrounds/tokyonight_original.png"

    [wallpaper.last]
    path = "/home/julio/dotfiles/others/backgrounds/tokyonight_original.png"

    [wallpaper.monitors.DP-1]
    path = "/home/julio/dotfiles/others/backgrounds/tokyonight_original.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/julio/Pictures/Wallpapers/tokyonight_original.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/julio/dotfiles/others/backgrounds/tokyonight_original.png"

[widget.Hibernate]
glyph = "hibernate"
type = "custom_button"

    [widget.Hibernate.actions]
    left = "exec exec pkexec systemctl hibernate"

[widget.clock]
format = "{:%-I:%M %p, %a %b %d}"

[widget.network]
show_label = false
